#!/bin/bash
# Controllers, Gazebo for Multiple Robots

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(dirname "$SCRIPT_DIR")"

source /opt/ros/humble/setup.bash
cd "$WORKSPACE_DIR"
source install/setup.bash

ros2 launch multi_arm_lab_sim_bringup multiple_ur.launch.py "$@"