# multi_arm_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true

    # Controller definitions
    arm1_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm2_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Parameters for each controller
arm1_joint_trajectory_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - arm1shoulder_pan_joint
      - arm1shoulder_lift_joint
      - arm1elbow_joint
      - arm1wrist_1_joint
      - arm1wrist_2_joint
      - arm1wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

arm2_joint_trajectory_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    joints:
      - arm1shoulder_pan_joint
      - arm1shoulder_lift_joint
      - arm1elbow_joint
      - arm1wrist_1_joint
      - arm1wrist_2_joint
      - arm1wrist_3_joint
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint