moveit_simple_controller_manager:
  controller_names:
    - arm_192_168_48_128_joint_trajectory_controller
  arm_192_168_48_128_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_192_168_48_128_shoulder_pan_joint
      - arm_192_168_48_128_shoulder_lift_joint
      - arm_192_168_48_128_elbow_joint
      - arm_192_168_48_128_wrist_1_joint
      - arm_192_168_48_128_wrist_2_joint
      - arm_192_168_48_128_wrist_3_joint
