# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:

  controller_manager_name: arm1/controller_manager

  controller_names:
    - arm1_ur3e_arm_controller

  arm1_ur3e_arm_controller:
    type: FollowJointTrajectory
    joints:
      - arm1_shoulder_pan_joint
      - arm1_shoulder_lift_joint
      - arm1_elbow_joint
      - arm1_wrist_1_joint
      - arm1_wrist_2_joint
      - arm1_wrist_3_joint