# Default initial positions for arm1's ros2_control fake system

initial_positions:
  arm1_elbow_joint: 0
  arm1_shoulder_lift_joint: 0
  arm1_shoulder_pan_joint: 0
  arm1_wrist_1_joint: 0
  arm1_wrist_2_joint: 0
  arm1_wrist_3_joint: 0