# In config/moveit_controllers.yaml
moveit_simple_controller_manager:
  controller_names:
    - /arm1_controller_manager/arm1_joint_trajectory_controller
    - /arm2_controller_manager/arm2_joint_trajectory_controller

  /arm1_controller_manager/arm1_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm1shoulder_pan_joint
      - arm1shoulder_lift_joint
      - arm1elbow_joint
      - arm1wrist_1_joint
      - arm1wrist_2_joint
      - arm1wrist_3_joint

  /arm2_controller_manager/arm2_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint