#!/bin/bash
# Usage: generate_joint_limits.sh <package_name> <pkg_dir> <robot1> <robot2> ...

PACKAGE_NAME="$1"
PKG_DIR="$2"
shift 2

out_file="${PKG_DIR}/config/joint_limits.yaml"
echo "# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed" > "$out_file"
echo "" >> "$out_file"
echo "# For beginners, we downscale velocity and acceleration limits." >> "$out_file"
echo "# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed." >> "$out_file"
echo "default_velocity_scaling_factor: 0.1" >> "$out_file"
echo "default_acceleration_scaling_factor: 0.1" >> "$out_file"
echo "" >> "$out_file"
echo "# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]" >> "$out_file"
echo "# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]" >> "$out_file"
echo "joint_limits:" >> "$out_file"
for robot in "$@"; do
  echo "  ${robot}_elbow_joint:" >> "$out_file"
  echo "    has_velocity_limits: true" >> "$out_file"
  echo "    max_velocity: 3.1415926535897931" >> "$out_file"
  echo "    has_acceleration_limits: false" >> "$out_file"
  echo "    max_acceleration: 0" >> "$out_file"
  echo "  ${robot}_shoulder_lift_joint:" >> "$out_file"
  echo "    has_velocity_limits: true" >> "$out_file"
  echo "    max_velocity: 3.1415926535897931" >> "$out_file"
  echo "    has_acceleration_limits: false" >> "$out_file"
  echo "    max_acceleration: 0" >> "$out_file"
  echo "  ${robot}_shoulder_pan_joint:" >> "$out_file"
  echo "    has_velocity_limits: true" >> "$out_file"
  echo "    max_velocity: 3.1415926535897931" >> "$out_file"
  echo "    has_acceleration_limits: false" >> "$out_file"
  echo "    max_acceleration: 0" >> "$out_file"
  echo "  ${robot}_wrist_1_joint:" >> "$out_file"
  echo "    has_velocity_limits: true" >> "$out_file"
  echo "    max_velocity: 6.2831853071795862" >> "$out_file"
  echo "    has_acceleration_limits: false" >> "$out_file"
  echo "    max_acceleration: 0" >> "$out_file"
  echo "  ${robot}_wrist_2_joint:" >> "$out_file"
  echo "    has_velocity_limits: true" >> "$out_file"
  echo "    max_velocity: 6.2831853071795862" >> "$out_file"
  echo "    has_acceleration_limits: false" >> "$out_file"
  echo "    max_acceleration: 0" >> "$out_file"
  echo "  ${robot}_wrist_3_joint:" >> "$out_file"
  echo "    has_velocity_limits: true" >> "$out_file"
  echo "    max_velocity: 6.2831853071795862" >> "$out_file"
  echo "    has_acceleration_limits: false" >> "$out_file"
  echo "    max_acceleration: 0" >> "$out_file"
done
