#!/bin/bash
# Usage: generate_ompl_planning.sh <package_name> <pkg_dir> <robot1> [<robot2> ...]
# Emits <pkg_dir>/config/ompl_planning.yaml with one planning-group block per arm
# (plus an all_arms group when there are >=2 arms), matching the SRDF groups.
#
# Key setting: a finer longest_valid_segment_fraction than MoveIt's default makes
# OMPL collision-check swept motions finely enough that path simplification
# cannot shortcut a link THROUGH a static collision object -- the cause of
# "Motion plan was found but it seems to be invalid (possibly due to
# postprocessing). Not executing." planner_configs is intentionally omitted so
# MoveItConfigsBuilder merges in the default planner definitions (RRTConnect, ...).

set -euo pipefail

PACKAGE_NAME="$1"
PKG_DIR="$2"
shift 2

if [ "$#" -eq 0 ]; then
  echo "[ERROR] No robot names provided to generate_ompl_planning.sh" >&2
  exit 1
fi

OUT_FILE="${PKG_DIR}/config/ompl_planning.yaml"
mkdir -p "${PKG_DIR}/config"

LVSF="0.005"   # longest_valid_segment_fraction (smaller = finer collision checking)
FIRST_ARM="$1"

{
  cat <<'HDR'
# OMPL planning config (generated by generate_ompl_planning.sh).
# Per-group longest_valid_segment_fraction is set fine so OMPL cannot shortcut a
# link through a static collision object during path simplification.
planning_plugin: ompl_interface/OMPLPlanner
start_state_max_bounds_error: 0.1
jiggle_fraction: 0.05
request_adapters: >-
    default_planner_request_adapters/AddTimeOptimalParameterization
    default_planner_request_adapters/ResolveConstraintFrames
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints
HDR

  for robot in "$@"; do
    echo ""
    echo "${robot}:"
    echo "  planner_configs:"
    echo "    - RRTConnect"
    echo "    - RRTstar"
    echo "  projection_evaluator: joints(${robot}_shoulder_pan_joint,${robot}_shoulder_lift_joint)"
    echo "  longest_valid_segment_fraction: ${LVSF}"
  done

  if [ "$#" -ge 2 ]; then
    echo ""
    echo "all_arms:"
    echo "  planner_configs:"
    echo "    - RRTConnect"
    echo "  projection_evaluator: joints(${FIRST_ARM}_shoulder_pan_joint,${FIRST_ARM}_shoulder_lift_joint)"
    echo "  longest_valid_segment_fraction: ${LVSF}"
  fi
} > "$OUT_FILE"

echo "Generated OMPL planning config: $OUT_FILE"
