#!/bin/bash
# Usage: generate_world_sdf.sh <package_name> <pkg_dir>
# Reads <pkg_dir>/config/robots.json and, if it contains a non-empty
# "static_objects" array, renders <pkg_dir>/config/world.sdf: the standard empty
# world (physics, plugins, sun, ground_plane) plus one static <model> per object.
# If there are no static objects, any stale world.sdf is removed so the package
# falls back to launching empty.sdf.

set -euo pipefail

PACKAGE_NAME="$1"
PKG_DIR="$2"

ROBOTS_JSON="${PKG_DIR}/config/robots.json"
OUT_FILE="${PKG_DIR}/config/world.sdf"
mkdir -p "${PKG_DIR}/config"

if [ ! -f "$ROBOTS_JSON" ]; then
  echo "[WARN] $ROBOTS_JSON not found; skipping world.sdf generation." >&2
  exit 0
fi

python3 - "$ROBOTS_JSON" "$OUT_FILE" <<'PY'
import json, sys, math

robots_json, out_file = sys.argv[1], sys.argv[2]
data = json.load(open(robots_json))
objects = data.get("static_objects") or []

# No static objects -> remove any stale world and bail (package uses empty.sdf).
if not objects:
    import os
    if os.path.exists(out_file):
        os.remove(out_file)
        print(f"[INFO] no static_objects; removed stale {out_file}")
    else:
        print("[INFO] no static_objects; nothing to generate")
    sys.exit(0)

# Standard empty-world preamble (mirrors Ignition's empty.sdf; world name kept
# "empty" so world-scoped gz topics match the default).
HEADER = '''<?xml version="1.0" ?>
<!-- generated by generate_world_sdf.sh from config/robots.json static_objects -->
<sdf version="1.6">
  <world name="empty">
    <physics name="1ms" type="ignored">
      <max_step_size>0.001</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="ignition-gazebo-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="ignition-gazebo-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="ignition-gazebo-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="ignition-gazebo-contact-system" name="gz::sim::systems::Contact"/>

    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.8 0.8 0.8 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <attenuation>
        <range>1000</range>
        <constant>0.9</constant>
        <linear>0.01</linear>
        <quadratic>0.001</quadratic>
      </attenuation>
      <direction>-0.5 0.1 -0.9</direction>
    </light>

    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>100 100</size></plane></geometry>
          <material>
            <ambient>0.8 0.8 0.8 1</ambient>
            <diffuse>0.8 0.8 0.8 1</diffuse>
            <specular>0.8 0.8 0.8 1</specular>
          </material>
        </visual>
      </link>
    </model>
'''

def geometry_xml(obj):
    if "box" in obj:
        sx, sy, sz = obj["box"]
        return f"<box><size>{sx} {sy} {sz}</size></box>"
    if "cylinder" in obj:
        c = obj["cylinder"]
        return f"<cylinder><radius>{c['radius']}</radius><length>{c['length']}</length></cylinder>"
    if "sphere" in obj:
        return f"<sphere><radius>{obj['sphere']['radius']}</radius></sphere>"
    if "mesh" in obj:
        s = obj.get("scale", 1.0)
        s = (s, s, s) if isinstance(s, (int, float)) else s
        return f"<mesh><uri>{obj['mesh']}</uri><scale>{s[0]} {s[1]} {s[2]}</scale></mesh>"
    return None

def model_xml(obj):
    name = obj["name"]
    p = obj["pose"]
    pose = f"{p[0]} {p[1]} {p[2]} {p[3]} {p[4]} {p[5]}"
    # Reusable model reference (model:// or package:// URI). Preferred over a bare
    # mesh for Gazebo so the model's own materials/textures load and it renders
    # solid. A sibling "mesh" field, if present, is ignored here and used only for
    # the MoveIt collision object (see scene_publisher.py).
    if "include" in obj:
        return (f'    <model name="{name}">\n'
                f'      <static>true</static>\n'
                f'      <pose>{pose}</pose>\n'
                f'      <include merge="true"><uri>{obj["include"]}</uri></include>\n'
                f'    </model>\n')
    geo = geometry_xml(obj)
    if geo is None:
        sys.stderr.write(f"[ERROR] static object '{name}' has no box/cylinder/sphere/include geometry\n")
        sys.exit(1)
    return (f'    <model name="{name}">\n'
            f'      <static>true</static>\n'
            f'      <pose>{pose}</pose>\n'
            f'      <link name="link">\n'
            f'        <collision name="collision"><geometry>{geo}</geometry></collision>\n'
            f'        <visual name="visual"><geometry>{geo}</geometry></visual>\n'
            f'      </link>\n'
            f'    </model>\n')

with open(out_file, "w") as f:
    f.write(HEADER)
    f.write("\n")
    for obj in objects:
        f.write(model_xml(obj))
    f.write("  </world>\n</sdf>\n")

print(f"[OK] wrote {out_file} with {len(objects)} static object(s): "
      + ", ".join(o['name'] for o in objects))
PY
