controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot1_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

robot1_joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot1_shoulder_pan_joint
      - robot1_shoulder_lift_joint
      - robot1_elbow_joint
      - robot1_wrist_1_joint
      - robot1_wrist_2_joint
      - robot1_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    robot2_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

robot2_joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot2_shoulder_pan_joint
      - robot2_shoulder_lift_joint
      - robot2_elbow_joint
      - robot2_wrist_1_joint
      - robot2_wrist_2_joint
      - robot2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

