moveit_simple_controller_manager:
  controller_names:
    - robot1_joint_trajectory_controller
    - robot2_joint_trajectory_controller
    - robot3_joint_trajectory_controller
  robot1_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot1_shoulder_pan_joint
      - robot1_shoulder_lift_joint
      - robot1_elbow_joint
      - robot1_wrist_1_joint
      - robot1_wrist_2_joint
      - robot1_wrist_3_joint
  robot2_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot2_shoulder_pan_joint
      - robot2_shoulder_lift_joint
      - robot2_elbow_joint
      - robot2_wrist_1_joint
      - robot2_wrist_2_joint
      - robot2_wrist_3_joint
  robot3_joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - robot3_shoulder_pan_joint
      - robot3_shoulder_lift_joint
      - robot3_elbow_joint
      - robot3_wrist_1_joint
      - robot3_wrist_2_joint
      - robot3_wrist_3_joint
