# In arm2_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm2_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm2_joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm2_shoulder_pan_joint
      - arm2_shoulder_lift_joint
      - arm2_elbow_joint
      - arm2_wrist_1_joint
      - arm2_wrist_2_joint
      - arm2_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity