version: 2

# Explicitly set the OS and Python versions
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt